# -*- coding: utf-8 -*-
"""Clase_04_ClasificacionResiduosMobileNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FD1IWENM44vD5OpcOln5sexon13_N0wn

# Clasificación de Residuos Sólidos con MobileNetV2  

**Docente:** Ing. M. Sc. Rudy Luis Manzaneda Veizaga  
**Tema:** Redes Neuronales Convolucionales, Transfer Learning y clasificación multiclase de imágenes.

# 1. Instalación y entorno
"""

import sys, platform
print("Python:", sys.version)
print("Sistema:", platform.platform())

!pip -q install -U scikit-learn seaborn -q

import os
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix, f1_score, roc_auc_score

print("TensorFlow:", tf.__version__)
print("GPU disponible:", tf.config.list_physical_devices("GPU"))

"""# 2. Google Drive y rutas

Estructura esperada:

```text
DataGarbage/
├── one-indexed-files-notrash_train.txt
├── one-indexed-files-notrash_val.txt
├── one-indexed-files-notrash_test.txt
└── Garbage classification/
    └── Garbage classification/
        ├── cardboard/
        ├── glass/
        ├── metal/
        ├── paper/
        ├── plastic/
        └── trash/
```
"""

from google.colab import drive
drive.mount("/content/drive")

BASE_PATH = Path("/content/drive/MyDrive/DataGarbage")
ZIP_PATH = Path("/content/drive/MyDrive/DataGarbage.zip")
IMAGE_BASE_PATH = BASE_PATH / "Garbage classification" / "Garbage classification"

TRAIN_SPLIT_FILE = "one-indexed-files-notrash_train.txt"
VAL_SPLIT_FILE   = "one-indexed-files-notrash_val.txt"
TEST_SPLIT_FILE  = "one-indexed-files-notrash_test.txt"

IMG_SIZE = (160, 160)
BATCH_SIZE = 32
SEED = 42
AUTOTUNE = tf.data.AUTOTUNE

np.random.seed(SEED)
tf.random.set_seed(SEED)

print("BASE_PATH:", BASE_PATH)
print("IMAGE_BASE_PATH:", IMAGE_BASE_PATH)
print("Existe BASE_PATH:", BASE_PATH.exists())
print("Existe IMAGE_BASE_PATH:", IMAGE_BASE_PATH.exists())

import kagglehub
import os
import zipfile

# Descargar dataset
path = kagglehub.dataset_download(
    "rudymanzaneda/datagarbage-rlmv"
)

print("Ruta descargada:", path)

# Mostrar contenido descargado
print("\nContenido:")
for archivo in os.listdir(path):
    print(archivo)

# Buscar y descomprimir automáticamente cualquier ZIP
for archivo in os.listdir(path):
    if archivo.endswith(".zip"):
        print(archivo)
        ruta_zip = os.path.join(path, archivo)

        carpeta_destino = os.path.join(
            path,
            archivo.replace(".zip", "")
        )

        with zipfile.ZipFile(ruta_zip, "r") as zip_ref:
            zip_ref.extractall(carpeta_destino)

        print(f"\nZIP descomprimido en:")
        print(carpeta_destino)

print("\nProceso finalizado.")

if not IMAGE_BASE_PATH.exists():
    if ZIP_PATH.exists():
        print("Dataset no encontrado. Descomprimiendo ZIP...")
        BASE_PATH.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
            zip_ref.extractall(BASE_PATH)
        print("Dataset descomprimido en:", BASE_PATH)
    else:
        print("No se encontró IMAGE_BASE_PATH ni ZIP_PATH. Verifica las rutas.")
else:
    print("Dataset ya disponible. No se requiere descompresión.")

"""# 3. Lectura de archivos de partición

Los archivos `.txt` contienen el nombre de la imagen y su etiqueta.  
Se resta 1 a la etiqueta porque muchas versiones del dataset están indexadas desde 1.
"""

label_map = {
    0: "glass",
    1: "paper",
    2: "plastic",
    3: "cardboard",
    4: "metal",
    5: "trash"
}

class_names = [label_map[i] for i in sorted(label_map.keys())]
num_classes = len(class_names)

print("Clases:", class_names)
print("Número de clases:", num_classes)

def load_split(split_filename, base_path=BASE_PATH):
    split_path = base_path / split_filename

    if not split_path.exists():
        raise FileNotFoundError(f"No existe el archivo de split: {split_path}")

    df = pd.read_csv(
        split_path,
        sep=r"\s+",
        header=None,
        names=["filename", "label"],
        engine="python"
    )

    df["label"] = df["label"].astype(int) - 1
    df["label_name"] = df["label"].map(label_map)
    return df

train_df = load_split(TRAIN_SPLIT_FILE)
val_df   = load_split(VAL_SPLIT_FILE)
test_df  = load_split(TEST_SPLIT_FILE)

print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

display(train_df.head())

"""# 4. Validación de rutas y corrección de etiquetas

Mejora importante: en vez de recorrer carpetas para cada imagen, primero se construye un índice rápido `filename → clase real`.  
Esto acelera la validación y reduce errores.
"""

def build_image_index(image_base_path):
    image_index = {}

    if not image_base_path.exists():
        raise FileNotFoundError(f"No existe la carpeta de imágenes: {image_base_path}")

    for class_folder in sorted(image_base_path.iterdir()):
        if class_folder.is_dir():
            label_name = class_folder.name
            for file_path in class_folder.iterdir():
                if file_path.is_file():
                    image_index[file_path.name] = label_name

    return image_index

image_index = build_image_index(IMAGE_BASE_PATH)

print("Imágenes indexadas:", len(image_index))
print("Ejemplos:", list(image_index.items())[:5])

inv_label_map = {v: k for k, v in label_map.items()}

def validate_and_correct_dataframe(df, image_index):
    df = df.copy()

    df["exists"] = df["filename"].isin(image_index)
    df["real_label_name"] = df["filename"].map(image_index)

    missing_count = int((~df["exists"]).sum())

    df = df[df["exists"]].copy()
    df["label_name"] = df["real_label_name"]
    df["label"] = df["label_name"].map(inv_label_map).astype(int)

    df["filepath"] = df.apply(
        lambda row: str(IMAGE_BASE_PATH / row["label_name"] / row["filename"]),
        axis=1
    )

    df = df.drop(columns=["exists", "real_label_name"])

    return df, missing_count

train_df, train_missing = validate_and_correct_dataframe(train_df, image_index)
val_df, val_missing     = validate_and_correct_dataframe(val_df, image_index)
test_df, test_missing   = validate_and_correct_dataframe(test_df, image_index)

print("Archivos faltantes en train:", train_missing)
print("Archivos faltantes en val:", val_missing)
print("Archivos faltantes en test:", test_missing)

print("Train validado:", train_df.shape)
print("Val validado:", val_df.shape)
print("Test validado:", test_df.shape)

display(train_df.head())

train_df

"""# 5. Análisis exploratorio del dataset

Antes de entrenar una CNN conviene revisar:

- cantidad de imágenes por clase,
- balance o desbalance,
- ejemplos visuales,
- posibles errores de etiqueta.

Esto es clave porque un dataset desbalanceado puede perjudicar a las clases minoritarias.
"""

def plot_class_distribution(df, title):
    counts = df["label_name"].value_counts().reindex(class_names)

    plt.figure(figsize=(10, 5))
    ax = sns.barplot(x=counts.index, y=counts.values)
    plt.title(title)
    plt.xlabel("Clase")
    plt.ylabel("Cantidad de imágenes")
    plt.xticks(rotation=30)

    for i, v in enumerate(counts.values):
        ax.text(i, v + max(counts.values)*0.01, str(int(v)), ha="center")

    plt.show()

plot_class_distribution(train_df, "Distribución de clases - Entrenamiento")
plot_class_distribution(val_df, "Distribución de clases - Validación")
plot_class_distribution(test_df, "Distribución de clases - Prueba")

summary_df = pd.DataFrame({
    "train": train_df["label_name"].value_counts().reindex(class_names),
    "val": val_df["label_name"].value_counts().reindex(class_names),
    "test": test_df["label_name"].value_counts().reindex(class_names),
}).fillna(0).astype(int)

summary_df["total"] = summary_df.sum(axis=1)
summary_df["porcentaje_total"] = (summary_df["total"] / summary_df["total"].sum() * 100).round(2)

display(summary_df)

from tensorflow.keras.utils import load_img

def show_examples_by_class(df, n_per_class=3):
    rows = num_classes
    cols = n_per_class

    plt.figure(figsize=(cols * 4, rows * 3.2))

    plot_idx = 1
    for class_name in class_names:
        class_df = df[df["label_name"] == class_name]
        sample = class_df.sample(n=min(n_per_class, len(class_df)), random_state=SEED)

        for _, row in sample.iterrows():
            img = load_img(row["filepath"], target_size=IMG_SIZE)
            plt.subplot(rows, cols, plot_idx)
            plt.imshow(img)
            plt.title(class_name)
            plt.axis("off")
            plot_idx += 1

    plt.tight_layout()
    plt.show()

show_examples_by_class(train_df, n_per_class=3)

"""# 6. Pesos de clase

Los pesos de clase ayudan cuando hay desbalance.  
Las clases con menos imágenes reciben mayor peso durante el entrenamiento.
"""

y_train = train_df["label"].values

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)

class_weights_dict = {
    int(class_id): float(weight)
    for class_id, weight in zip(np.unique(y_train), class_weights)
}

for class_id, weight in class_weights_dict.items():
    print(f"{class_id} - {label_map[class_id]}: {weight:.4f}")

""">👉 Este código calcula pesos para cada clase con el objetivo de compensar clases desbalanceadas.

# 7. Pipeline `tf.data`

Mejora metodológica importante:

- Entrenamiento: preprocesamiento + aumento de datos.
- Validación y prueba: solo preprocesamiento.

No se debe aplicar aumento aleatorio a validación/prueba porque altera la evaluación.
"""

# Capa de aumento de datos para generar nuevas variaciones de imágenes
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.08),
    layers.RandomZoom(0.12),
    layers.RandomContrast(0.15),
], name="data_augmentation")

# Lee una imagen desde disco y la convierte a tensor normalizado
def load_image(filepath, label):
    image_bytes = tf.io.read_file(filepath)
    image = tf.image.decode_image(image_bytes, channels=3, expand_animations=False)
    image = tf.image.convert_image_dtype(image, tf.float32)
    return image, label

# Redimensiona la imagen y aplica el preprocesamiento de MobileNetV2
def preprocess_for_mobilenet(image, label):
    image = tf.image.resize(image, IMG_SIZE)
    image = image * 255.0
    image = preprocess_input(image)
    return image, label

# Aplica transformaciones aleatorias durante el entrenamiento
def augment_train(image, label):
    image = data_augmentation(image, training=True)
    return image, label

def dataframe_to_dataset(df, training=False):
    filepaths = df["filepath"].values
    labels = df["label"].astype("int32").values

    ds = tf.data.Dataset.from_tensor_slices((filepaths, labels))

    if training:
        ds = ds.shuffle(buffer_size=len(df), seed=SEED, reshuffle_each_iteration=True)

    ds = ds.map(load_image, num_parallel_calls=AUTOTUNE)
    ds = ds.map(preprocess_for_mobilenet, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.map(augment_train, num_parallel_calls=AUTOTUNE)

    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)

    return ds

train_ds = dataframe_to_dataset(train_df, training=True)
val_ds   = dataframe_to_dataset(val_df, training=False)
test_ds  = dataframe_to_dataset(test_df, training=False)

print(train_ds)
print(val_ds)
print(test_ds)

# Inspecciona el primer lote del dataset para validar dimensiones, rango de valores y etiquetas
# Verifica que las imágenes y etiquetas fueron cargadas y preprocesadas correctamente
for images, labels in train_ds.take(1):
    print("Shape de imágenes:", images.shape)
    print("Shape de etiquetas:", labels.shape)
    print("Rango mínimo:", tf.reduce_min(images).numpy())
    print("Rango máximo:", tf.reduce_max(images).numpy())
    print("Etiquetas:", labels.numpy()[:10])

"""# 8. Modelo MobileNetV2 con Transfer Learning

MobileNetV2 ya aprendió patrones generales en ImageNet: bordes, texturas, formas y objetos.  
Aquí reutilizamos ese conocimiento y cambiamos la cabeza final para clasificar residuos.
"""

IMG_SIZE

input_shape = IMG_SIZE + (3,)

# Modelo base preentrenado
base_model = MobileNetV2(
    input_shape=input_shape,
    include_top=False,
    weights="imagenet"
)

# Congelamos MobileNetV2
base_model.trainable = False

num_classes

model = keras.Sequential([
    layers.Input(shape=input_shape, name="imagen_entrada"),
    # Base convolucional preentrenada
    base_model,
    layers.GlobalAveragePooling2D(name="global_average_pooling"),

    layers.Dropout(0.30, name="dropout_1"),

    # Capa densa de clasificación
    layers.Dense(128, activation="relu", name="dense_128"),

    # Regularización adicional
    layers.Dropout(0.25, name="dropout_2"),

    # Capa de salida multiclase
    layers.Dense(num_classes, activation="softmax", name="salida_softmax")
],name="MobileNetV2_Garbage_Classifier")

# Compilación
model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Resumen
model.summary()

"""CALLBACKS"""

CHECKPOINT_PATH = "best_mobilenetv2_garbage.keras"

# Detiene el entrenamiento si la pérdida de validación deja de mejorar
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True,
    verbose=1
)

# Reduce automáticamente la tasa de aprendizaje cuando el modelo se estanca
lr_scheduler = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6,
    verbose=1
)

# Guarda automáticamente el mejor modelo durante el entrenamiento
checkpoint = ModelCheckpoint(
    CHECKPOINT_PATH,
    monitor="val_loss",
    save_best_only=True,
    mode="min",
    verbose=1
)

callbacks = [early_stopping, lr_scheduler, checkpoint]

"""ENTRENAMIENTO"""

EPOCHS_INITIAL = 15

history_initial = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_INITIAL,
    callbacks=callbacks,
    class_weight=class_weights_dict,
    verbose=1
)

def plot_history(history, title="Historial de entrenamiento"):
    hist = history.history

    plt.figure(figsize=(14, 5))

    plt.subplot(1, 2, 1)
    plt.plot(hist["accuracy"], label="Entrenamiento")
    plt.plot(hist["val_accuracy"], label="Validación")
    plt.title(f"{title} - Accuracy")
    plt.xlabel("Época")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.grid(alpha=0.3)

    plt.subplot(1, 2, 2)
    plt.plot(hist["loss"], label="Entrenamiento")
    plt.plot(hist["val_loss"], label="Validación")
    plt.title(f"{title} - Loss")
    plt.xlabel("Época")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(alpha=0.3)

    plt.tight_layout()
    plt.show()

plot_history(history_initial, title="Entrenamiento inicial")

"""FINE-TUNING"""

base_model.trainable = True
#"Voy a descongelar las últimas 40 capas de MobileNetV2 para realizar Fine-Tuning".
FINE_TUNE_AT = len(base_model.layers) - 40
print(FINE_TUNE_AT)

for layer in base_model.layers[:FINE_TUNE_AT]:
    layer.trainable = False

print("Total de capas en MobileNetV2:", len(base_model.layers))
print("Capas entrenables desde:", FINE_TUNE_AT)
print("Capas entrenables en base_model:", sum([layer.trainable for layer in base_model.layers]))

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

EPOCHS_FINE_TUNE = 20

history_finetune = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS_FINE_TUNE,
    callbacks=callbacks,
    class_weight=class_weights_dict,
    verbose=1
)

plot_history(history_finetune, title="Fine-tuning")

y_true = test_df["label"].values
y_pred_probs = model.predict(test_ds, verbose=1)
y_pred = np.argmax(y_pred_probs, axis=1)

print("Classification Report:")
print(classification_report(
    y_true,
    y_pred,
    target_names=class_names,
    digits=4
))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(9, 7))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)
plt.title("Matriz de confusión - Clasificación de residuos")
plt.xlabel("Predicción")
plt.ylabel("Clase real")
plt.xticks(rotation=30)
plt.yticks(rotation=0)
plt.show()

f1_macro = f1_score(y_true, y_pred, average="macro")
print(f"F1-score macro: {f1_macro:.4f}")

try:
    y_true_onehot = keras.utils.to_categorical(y_true, num_classes=num_classes)
    roc_macro = roc_auc_score(y_true_onehot, y_pred_probs, multi_class="ovr", average="macro")
    print(f"ROC AUC macro (OvR): {roc_macro:.4f}")
except Exception as e:
    print("No fue posible calcular ROC AUC multiclase:", e)

"""Análisis visual de aciertos y errores"""

results_df = test_df.copy().reset_index(drop=True)

results_df["pred_label"] = y_pred
results_df["pred_label_name"] = results_df["pred_label"].map(label_map)
results_df["confidence"] = np.max(y_pred_probs, axis=1)
results_df["correct"] = results_df["label"] == results_df["pred_label"]

display(results_df.head())
print("Accuracy manual:", results_df["correct"].mean())

# Muestra ejemplos de imágenes clasificadas correctamente o incorrectamente por el modelo
def show_prediction_examples(df_results, correct=True, n=9):
    subset = df_results[df_results["correct"] == correct]

    if len(subset) == 0:
        print("No hay ejemplos para mostrar.")
        return

    sample = subset.sample(n=min(n, len(subset)), random_state=SEED)

    plt.figure(figsize=(14, 10))
    for i, (_, row) in enumerate(sample.iterrows(), start=1):
        img = load_img(row["filepath"], target_size=IMG_SIZE)

        plt.subplot(3, 3, i)
        plt.imshow(img)
        plt.axis("off")

        title = (
            f"Real: {row['label_name']}\n"
            f"Pred: {row['pred_label_name']} ({row['confidence']:.2f})"
        )

        plt.title(title, color="green" if row["correct"] else "red")

    plt.tight_layout()
    plt.show()

print("Ejemplos correctamente clasificados")
show_prediction_examples(results_df, correct=True, n=9)

print("Ejemplos mal clasificados")
show_prediction_examples(results_df, correct=False, n=9)

"""Guardado del Modelo Final"""

MODEL_DIR = Path("models")
MODEL_DIR.mkdir(exist_ok=True)

final_model_path = MODEL_DIR / "garbage_classifier_mobilenetv2_pro.keras"
model.save(final_model_path)

print("Modelo guardado en:", final_model_path)